// Velcora Media — premium interactions + project enquiry flow
(() => {
  const nav=document.getElementById('nav'),dot=document.querySelector('.cursor-dot'),ring=document.querySelector('.cursor-ring');
  document.body.classList.remove('login-locked'); document.documentElement.style.overflowY='auto'; document.body.style.overflowY='auto';
  window.addEventListener('scroll',()=>{nav?.classList.toggle('scrolled',scrollY>30);const max=document.documentElement.scrollHeight-innerHeight;const bar=document.querySelector('.page-progress');if(bar)bar.style.width=`${max>0?scrollY/max*100:0}%`},{passive:true});
  const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
  if(matchMedia('(pointer:fine)').matches){let mx=innerWidth/2,my=innerHeight/2,rx=mx,ry=my;addEventListener('pointermove',e=>{mx=e.clientX;my=e.clientY;if(dot)dot.style.transform=`translate3d(${mx}px,${my}px,0)`});const loop=()=>{rx+=(mx-rx)*.12;ry+=(my-ry)*.12;if(ring)ring.style.transform=`translate3d(${rx}px,${ry}px,0)`;requestAnimationFrame(loop)};loop();document.querySelectorAll('a,button').forEach(el=>{el.addEventListener('mouseenter',()=>document.body.classList.add('cursor-active'));el.addEventListener('mouseleave',()=>document.body.classList.remove('cursor-active'))});document.querySelectorAll('.magnetic').forEach(el=>{el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect();el.style.transform=`translate(${(e.clientX-r.left-r.width/2)*.12}px,${(e.clientY-r.top-r.height/2)*.12}px)`});el.addEventListener('pointerleave',()=>el.style.transform='')})}
  const art=document.querySelector('.hero-art'),v3d=document.querySelector('.v-3d');if(art&&v3d&&matchMedia('(pointer:fine)').matches){art.addEventListener('pointermove',e=>{const r=art.getBoundingClientRect(),px=(e.clientX-r.left)/r.width-.5,py=(e.clientY-r.top)/r.height-.5;v3d.style.animationPlayState='paused';v3d.style.transform=`rotateX(${18-py*12}deg) rotateY(${-24+px*18}deg) rotateZ(-7deg) translateY(${py*-12}px)`});art.addEventListener('pointerleave',()=>v3d.style.animationPlayState='running')}
  const menu=document.querySelector('.menu'),navLinks=document.querySelector('.nav-links');if(menu)menu.addEventListener('click',()=>{const open=navLinks.classList.toggle('open');menu.setAttribute('aria-expanded',String(open))});document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',()=>navLinks?.classList.remove('open')));
  const modal=document.createElement('div');modal.className='project-modal';modal.innerHTML=`<div class="project-modal-backdrop" data-close></div><div class="project-modal-card" role="dialog" aria-modal="true" aria-labelledby="projectModalTitle"><button class="project-modal-close" type="button" data-close aria-label="Close">×</button><div class="section-kicker">Start a project</div><h2 id="projectModalTitle">Tell us what<br><em>you're building.</em></h2><p class="project-modal-intro">Share a few details and we'll open WhatsApp with everything organised in one message.</p><form id="projectForm"><label>Name<input name="name" type="text" placeholder="Your name" required></label><label>Email<input name="email" type="email" placeholder="you@company.com" required></label><label>Project category<select name="category" required><option value="">Choose a category</option><option>Shopify Store</option><option>Dropshipping Store</option><option>Personal Brand</option><option>Fashion / Clothing</option><option>Business Website</option><option>SaaS / AI</option><option>Landing Page</option><option>Portfolio / Creative</option><option>Other</option></select></label><label>What do you need?<textarea name="details" rows="4" placeholder="Brand, products, pages, features, references or goals..."></textarea></label><label>Budget range<select name="budget"><option value="">Select budget</option><option>Under $100</option><option>$100–$250</option><option>$250–$500</option><option>$500–$1,000</option><option>$1,000+</option><option>Not sure yet</option></select></label><button class="project-modal-submit" type="submit">Continue to WhatsApp <span>↗</span></button></form></div>`;document.body.appendChild(modal);
  const openModal=e=>{e.preventDefault();modal.classList.add('is-open');document.body.classList.add('modal-open');setTimeout(()=>modal.querySelector('input')?.focus(),80)};document.querySelectorAll('a[href*="wa.me"]').forEach(btn=>btn.addEventListener('click',openModal));
  modal.addEventListener('click',e=>{if(e.target.closest('[data-close]')){modal.classList.remove('is-open');document.body.classList.remove('modal-open')}});
  modal.querySelector('#projectForm')?.addEventListener('submit',e=>{e.preventDefault();const d=new FormData(e.currentTarget);const msg=`Hi Velcora Media, I'd like to start a website project.\n\nName: ${d.get('name')}\nEmail: ${d.get('email')}\nCategory: ${d.get('category')}\nBudget: ${d.get('budget')||'Not specified'}\nProject details: ${d.get('details')||'Not specified'}`;window.open(`https://wa.me/919769772615?text=${encodeURIComponent(msg)}`,'_blank','noopener');modal.classList.remove('is-open');document.body.classList.remove('modal-open')});document.addEventListener('keydown',e=>{if(e.key==='Escape'){modal.classList.remove('is-open');document.body.classList.remove('modal-open')}});
  // Category cards: open the complete category-specific showcase instead of jumping to contact.
  const demos=['demos/shopify-store.html','demos/dropshipping.html','demos/personal-brand.html','demos/fashion-clothing.html','demos/business.html','demos/saas-ai.html','demos/landing-page.html','demos/creative-portfolio.html'];
  document.querySelectorAll('.category-card').forEach((card,i)=>{if(demos[i])card.setAttribute('href',demos[i])});
  // The old multi-image reference gallery is intentionally hidden; category cards are now the portfolio entry point.
  document.querySelector('#work')?.remove();
  if(matchMedia('(prefers-reduced-motion: reduce)').matches){document.documentElement.style.scrollBehavior='auto';document.querySelectorAll('*').forEach(el=>{el.style.animationDuration='.001ms';el.style.transitionDuration='.001ms'})}
})();