// Velcora Media — premium interactions, lead capture and concierge
(()=>{const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
// Keep the homepage focused: categories are the showcase entry point.
$('#work')?.remove();$('.nav-links a[href="#work"]')?.remove();
const demos=['demos/shopify-store.html','demos/dropshipping.html','demos/personal-brand.html','demos/fashion-clothing.html','demos/business.html','demos/saas-ai.html','demos/landing-page.html','demos/creative-portfolio.html'];
$$('.category-card').forEach((c,i)=>{if(demos[i])c.href=demos[i];c.setAttribute('aria-label',`Open ${$('h3',c)?.textContent||'website'} demo`)});
$('html').style.overflowY='auto';document.body.style.overflowY='auto';
const nav=$('#nav');addEventListener('scroll',()=>nav?.classList.toggle('scrolled',scrollY>30),{passive:true});
const ob=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');ob.unobserve(e.target)}}),{threshold:.12});$$('.reveal').forEach(e=>ob.observe(e));
const menu=$('.menu'),nl=$('.nav-links');menu?.addEventListener('click',()=>{const o=nl.classList.toggle('open');menu.setAttribute('aria-expanded',o)});$$('a[href^="#"]').forEach(a=>a.addEventListener('click',()=>nl?.classList.remove('open')));
const art=$('.hero-art'),v=$('.v-3d');if(art&&v&&matchMedia('(pointer:fine)').matches){art.addEventListener('pointermove',e=>{const r=art.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;v.style.animationPlayState='paused';v.style.transform=`rotateX(${18-y*12}deg) rotateY(${-24+x*18}deg) rotateZ(-7deg) translateY(${y*-12}px)`});art.addEventListener('pointerleave',()=>v.style.animationPlayState='running')}
// Project brief modal: collect the complete brief before WhatsApp.
const modal=document.createElement('div');modal.className='project-modal';modal.innerHTML=`<div class="project-modal-backdrop" data-close></div><div class="project-modal-card" role="dialog" aria-modal="true"><button class="project-modal-close" data-close>×</button><div class="section-kicker">Start a project</div><h2>Tell us what<br><em>you're building.</em></h2><p class="project-modal-intro">Give us the details once. We'll organise the brief and open WhatsApp.</p><form id="projectForm"><label>Name<input name="name" placeholder="Your name" required></label><label>Business / Brand<input name="brand" placeholder="Brand or company" required></label><label>Email<input name="email" type="email" placeholder="you@company.com" required></label><label>Website type<select name="category" required><option value="">Choose a category</option><option>Shopify Store</option><option>Dropshipping Store</option><option>Personal Brand</option><option>Fashion / Clothing</option><option>Business Website</option><option>SaaS / AI</option><option>Landing Page</option><option>Portfolio / Creative</option><option>Other</option></select></label><label>Target market<select name="market"><option>US</option><option>UK</option><option>Canada</option><option>Australia</option><option>Europe</option><option>India</option><option>Worldwide</option></select></label><label>Budget range<select name="budget"><option value="">Select budget</option><option>Under $100</option><option>$100–$250</option><option>$250–$500</option><option>$500–$1,000</option><option>$1,000+</option><option>Not sure yet</option></select></label><label>Project details<textarea name="details" rows="4" placeholder="Products, pages, features, references, deadline, goals..."></textarea></label><button class="project-modal-submit">Continue to WhatsApp <span>↗</span></button></form></div>`;document.body.appendChild(modal);
const open=e=>{e.preventDefault();modal.classList.add('is-open');document.body.classList.add('modal-open');setTimeout(()=>modal.querySelector('input')?.focus(),80)};$$('a[href*="wa.me"]').forEach(a=>a.addEventListener('click',open));modal.addEventListener('click',e=>{if(e.target.closest('[data-close]')){modal.classList.remove('is-open');document.body.classList.remove('modal-open')}});$('#projectForm',modal).addEventListener('submit',e=>{e.preventDefault();const d=new FormData(e.currentTarget);const msg=`Hi Velcora Media, I'd like to start a website project.\n\nName: ${d.get('name')}\nBrand: ${d.get('brand')}\nEmail: ${d.get('email')}\nCategory: ${d.get('category')}\nTarget market: ${d.get('market')}\nBudget: ${d.get('budget')||'Not specified'}\nDetails: ${d.get('details')||'Not specified'}`;window.open(`https://wa.me/919769772615?text=${encodeURIComponent(msg)}`,'_blank','noopener');window.location.href='mailto:hello.velcoramedia@gmail.com?subject=New Velcora project enquiry&body='+encodeURIComponent(msg);modal.classList.remove('is-open');document.body.classList.remove('modal-open')});addEventListener('keydown',e=>{if(e.key==='Escape'){modal.classList.remove('is-open');document.body.classList.remove('modal-open')}});
// Small Velcora-branded AI concierge.
const css=document.createElement('style');css.textContent=`.vc-chat{position:fixed;right:22px;bottom:22px;z-index:9999;font-family:inherit}.vc-chat-btn{width:56px;height:56px;border:1px solid #3d3f44;border-radius:50%;background:#0b0c0f;color:#fff;display:grid;place-items:center;box-shadow:0 16px 50px #0009;cursor:pointer}.vc-logo{width:30px;height:30px;border:1px solid #fff;border-radius:9px;display:grid;place-items:center;font-size:14px;font-weight:900;letter-spacing:-.08em}.vc-chat-panel{position:absolute;right:0;bottom:68px;width:min(370px,calc(100vw - 28px));background:#101114;color:#f7f7f4;border:1px solid #303136;border-radius:20px;overflow:hidden;box-shadow:0 25px 80px #000b;display:none}.vc-chat-panel.open{display:block}.vc-chat-head{padding:16px 18px;border-bottom:1px solid #292a2e;display:flex;justify-content:space-between}.vc-chat-head small{opacity:.5}.vc-chat-msgs{height:275px;overflow:auto;padding:16px}.vc-msg{max-width:88%;padding:10px 12px;border-radius:13px;margin-bottom:9px;font-size:12px;line-height:1.5}.vc-ai{background:#1c1d21}.vc-user{background:#f4f4f0;color:#111;margin-left:auto}.vc-chat-form{display:flex;gap:7px;padding:10px;border-top:1px solid #292a2e}.vc-chat-form input{min-width:0;flex:1;background:#18191d;color:#fff;border:1px solid #33353a;border-radius:11px;padding:10px}.vc-chat-form button{border:0;border-radius:11px;padding:0 13px;background:#f4f4f0;color:#111;font-weight:800}@media(max-width:600px){.vc-chat{right:13px;bottom:13px}.vc-chat-btn{width:52px;height:52px}.vc-chat-panel{bottom:62px;width:calc(100vw - 26px)}}`;document.head.appendChild(css);
const chat=document.createElement('div');chat.className='vc-chat';chat.innerHTML=`<div class="vc-chat-panel"><div class="vc-chat-head"><div><strong>Velcora Concierge</strong><br><small>Website project assistant</small></div><button type="button" class="vc-close" style="background:none;border:0;color:#fff;font-size:19px">×</button></div><div class="vc-chat-msgs"><div class="vc-msg vc-ai">Hi 👋 I'm Velcora's assistant. Tell me what kind of website you're planning.</div></div><form class="vc-chat-form"><input aria-label="Message" placeholder="Ask about Shopify, fashion..." autocomplete="off"><button>Send</button></form></div><button class="vc-chat-btn" aria-label="Open Velcora Concierge"><span class="vc-logo">V</span></button>`;document.body.appendChild(chat);const panel=$('.vc-chat-panel',chat),msgs=$('.vc-chat-msgs',chat),input=$('input',chat);$('.vc-chat-btn',chat).onclick=()=>panel.classList.toggle('open');$('.vc-close',chat).onclick=()=>panel.classList.remove('open');$('form',chat).onsubmit=e=>{e.preventDefault();const q=input.value.trim();if(!q)return;const u=document.createElement('div');u.className='vc-msg vc-user';u.textContent=q;msgs.appendChild(u);const l=q.toLowerCase();let a='Tell me your business, target country, website type and goal. For a full quote, use Start a project.';if(/shopify|store|ecommerce/.test(l))a='For Shopify, we recommend a premium product-first store with collections, product pages, reviews, cart UX and strong mobile conversion.';else if(/drop|product|winning/.test(l))a='For dropshipping, we can build a branded DTC store with a strong product story, trust, reviews, offers and conversion-focused checkout journey.';else if(/fashion|cloth/.test(l))a='For fashion, we recommend an editorial brand experience with large imagery, collections, lookbook, product storytelling and premium typography.';else if(/usa|uk|canada|australia|tier/.test(l))a='Yes. Velcora is positioned for Tier‑1 audiences with English-first copy, premium design and international-ready UX.';else if(/email|contact/.test(l))a='You can reach Velcora at hello.velcoramedia@gmail.com.';setTimeout(()=>{const ai=document.createElement('div');ai.className='vc-msg vc-ai';ai.textContent=a;msgs.appendChild(ai);msgs.scrollTop=msgs.scrollHeight},260);input.value=''};
})();