// Velcora Media — interactions + Apple-style scroll-driven 3D hero
(()=>{
 const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
 const demos=['demos/shopify-store.html','demos/dropshipping.html','demos/personal-brand.html','demos/fashion-clothing.html','demos/business.html','demos/saas-ai.html','demos/landing-page.html','demos/creative-portfolio.html'];
 $$('.category-card').forEach((c,i)=>{if(demos[i])c.href=demos[i]});
 document.documentElement.style.overflowY='auto';document.body.style.overflowY='auto';
 const nav=$('#nav');addEventListener('scroll',()=>nav?.classList.toggle('scrolled',scrollY>30),{passive:true});
 const menu=$('.menu'),links=$('.nav-links');menu?.addEventListener('click',()=>{const o=links?.classList.toggle('open');menu.setAttribute('aria-expanded',String(!!o))});
 $$('a[href^="#"]').forEach(a=>a.addEventListener('click',()=>links?.classList.remove('open')));
 const ro=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');ro.unobserve(e.target)}}),{threshold:.12});$$('.reveal').forEach(e=>ro.observe(e));
 const hero=$('.hero'),art=$('.hero-art'),obj=$('.v-3d'),reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;
 if(hero&&art&&obj&&!reduce){let raf=0;const update=()=>{raf=0;const r=hero.getBoundingClientRect(),travel=Math.max(1,hero.offsetHeight-innerHeight*.55),p=Math.min(1,Math.max(0,-r.top/travel));obj.style.transform=`translate3d(${p*72}px,${p*-34}px,${p*-90}px) rotateX(${12-p*22}deg) rotateY(${-24+p*62}deg) rotateZ(${-7+p*210}deg) scale(${1-p*.54})`;obj.style.opacity=String(1-p*.42)};const tick=()=>{if(!raf)raf=requestAnimationFrame(update)};addEventListener('scroll',tick,{passive:true});addEventListener('resize',tick,{passive:true});update()}
 // AI assistant intentionally removed from the main site.
 const modal=document.createElement('div');modal.className='project-modal';modal.innerHTML=`<div class="project-modal-backdrop" data-close></div><div class="project-modal-card" role="dialog" aria-modal="true"><button class="project-modal-close" data-close aria-label="Close">×</button><div class="section-kicker">Start a project</div><h2>Tell us what<br><em>you're building.</em></h2><p class="project-modal-intro">Share the essentials once. We'll prepare the brief for WhatsApp.</p><form id="projectForm"><label>Name<input name="name" placeholder="Your name" required></label><label>Business / Brand<input name="brand" placeholder="Brand or company" required></label><label>Email<input name="email" type="email" placeholder="you@company.com" required></label><label>Website type<select name="category" required><option value="">Choose a category</option><option>Shopify Store</option><option>Dropshipping Store</option><option>Personal Brand</option><option>Fashion / Clothing</option><option>Business Website</option><option>SaaS / AI</option><option>Landing Page</option><option>Portfolio / Creative</option><option>Other</option></select></label><label>Target market<select name="market"><option>US</option><option>UK</option><option>Canada</option><option>Australia</option><option>Europe</option><option>India</option><option>Worldwide</option></select></label><label>Budget range<select name="budget"><option value="">Select budget</option><option>Under $100</option><option>$100–$250</option><option>$250–$500</option><option>$500–$1,000</option><option>$1,000+</option><option>Not sure yet</option></select></label><label>Project details<textarea name="details" rows="4" placeholder="Products, pages, features, references, deadline, goals..."></textarea></label><button class="project-modal-submit">Continue to WhatsApp <span>↗</span></button></form></div>`;document.body.appendChild(modal);
 const open=e=>{e.preventDefault();modal.classList.add('is-open');document.body.classList.add('modal-open');setTimeout(()=>modal.querySelector('input')?.focus(),80)};$$('a[href*="wa.me"]').forEach(a=>a.addEventListener('click',open));modal.addEventListener('click',e=>{if(e.target.closest('[data-close]')){modal.classList.remove('is-open');document.body.classList.remove('modal-open')}});
 $('#projectForm',modal)?.addEventListener('submit',e=>{e.preventDefault();const d=new FormData(e.currentTarget),msg=`Hi Velcora Media, I'd like to start a website project.\n\nName: ${d.get('name')}\nBrand: ${d.get('brand')}\nEmail: ${d.get('email')}\nCategory: ${d.get('category')}\nTarget market: ${d.get('market')}\nBudget: ${d.get('budget')||'Not specified'}\nDetails: ${d.get('details')||'Not specified'}`;window.open(`https://wa.me/919769772615?text=${encodeURIComponent(msg)}`,'_blank','noopener');modal.classList.remove('is-open');document.body.classList.remove('modal-open')});
 addEventListener('keydown',e=>{if(e.key==='Escape'){modal.classList.remove('is-open');document.body.classList.remove('modal-open')}});
})();